include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cfip-lite
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for CFIP Lite
LUCI_DEPENDS:=+luci-base +python3-light +python3-requests
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
